# Site Settings
baseurl: 		"/cookbiz"
title: 			CookBiz!

name: 			CookBiz!
description: 	
# url: 			"http://localhost:4000"
url:            "//frankchen07.github.io"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		
email: 			frankchen07@gmail.com

disqus: 		placeholder
analytics: 		UA-XXXXXXX-Y	

copyright: 		Copyright 2017 CookBiz!

# Build Settings
permalinks: 	pretty

# Gems
gems: [jekyll-paginate]