# Site Settings
baseurl: 		""
title: 			CookBiz!

name: 			Cookbiz!
description: 	
url: 			"http://localhost:4000"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		placeholder
email: 			placeholder@placeholder.com

disqus: 		placeholder
analytics: 		UA-XXXXXXX-Y	

copyright: 		Copyright 2017 Cookbiz!

# Build Settings
permalinks: 	pretty

# Gems
gems: [jekyll-paginate]